# Image form https://quay.io/repository/wildfly/wildfly
FROM quay.io/wildfly/wildfly

# Copy war file in to server directory. App will start automatically
ADD target/backend.war /opt/jboss/wildfly/standalone/deployments/


